//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int idEmpleado { get; set; }
        public string nombreEmpleado { get; set; }
        public string apellidosEmpleado { get; set; }
        public string cedulaEmpleado { get; set; }
        public string generoEmpleado { get; set; }
        public System.DateTime fechaContratacionEmpleado { get; set; }
        public string direccionEmpleado { get; set; }
        public bool estadoEmpleado { get; set; }
        public int idPuesto { get; set; }
    
        public virtual Puestos Puestos { get; set; }
    }
}
